export const OBTER_USUARIOS = "OBTER_USUARIOS";
export const OBTER_USUARIOS_SUCCESS = "OBTER_USUARIOS_SUCCESS";

export const OBTER_USUARIO = "OBTER_USUARIO";
export const OBTER_USUARIO_SUCCESS = "OBTER_USUARIO_SUCCESS";

export const CADASTRAR_USUARIO = "CADASTRAR_USUARIO";
export const CADASTRAR_USUARIO_SUCCESS = "CADASTRAR_USUARIO_SUCCESS";

export const ATUALIZAR_USUARIO = "ATUALIZAR_USUARIO";
export const ATUALIZAR_USUARIO_SUCCESS = "ATUALIZAR_USUARIO_SUCCESS";

export const EXCLUIR_USUARIO = "EXCLUIR_USUARIO";
export const EXCLUIR_USUARIO_SUCCESS = "EXCLUIR_USUARIO_SUCCESS";

export const EXIBIR_MODAL_FORMULARIO_USUARIO = "EXIBIR_MODAL_FORMULARIO_USUARIO";
export const ESCONDER_MODAL_FORMULARIO_USUARIO = "ESCONDER_MODAL_FORMULARIO_USUARIO";

export const EXIBIR_MODAL_EXCLUIR_USUARIO = "EXIBIR_MODAL_EXCLUIR_USUARIO";
export const ESCONDER_MODAL_EXCLUIR_USUARIO = "ESCONDER_MODAL_EXCLUIR_USUARIO";